kafka_server : "localhost:29092"
kafka_broker-topic : "broker-repo"
kafka_repo-topic : "repo-broker"

database:
  host: localhost:3306
  username: root
  password: example
  schema: hotel_db
server:
  port: :8084

